name: my_deficiencies
description: "A new Flutter project."
publish_to: "none"

version: 2.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_svg: ^2.2.0
  cached_network_image: ^3.4.1
  #  google_fonts: ^6.2.1
  fluttertoast: ^8.2.12
  shared_preferences: ^2.5.3

  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  firebase_analytics: ^11.5.0
  firebase_database: ^11.3.7
  sign_in_with_apple: ^7.0.1

  #  chat_gpt_sdk: ^3.1.5
  #  flutter_spinkit: ^5.2.1
  #  animated_text_kit: ^4.2.3

  lottie: ^3.3.1
  share_plus: ^11.0.0
  #  speech_to_text: ^7.0.0
  #  package_info_plus: ^8.3.0
  #  audioplayers: ^6.4.0
  clipboard: ^0.1.3

  in_app_purchase: ^3.2.1
  in_app_purchase_storekit: ^0.3.22+1
  url_launcher: ^6.3.1
  gradient_borders: ^1.0.1
  intl: ^0.20.2
  flutter_html: ^3.0.0
  flutter_html_table: ^3.0.0
  firebase_remote_config: ^5.4.7
  flutter_html_iframe: ^3.0.0

  flutter_widget_from_html: ^0.16.0
  http: ^1.4.0

  app_tracking_transparency: ^2.0.6+1

  sqflite: ^2.4.2
  path: ^1.9.1

  #  flutter_to_pdf: ^0.4.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  file_saver: ^0.3.0
  flutter_markdown_plus: ^1.0.3
  html_unescape: ^2.0.0

  shimmer: ^3.0.0
  pull_down_button: ^0.10.2
  pdf: ^3.11.3
  file_picker: ^10.2.0
  selectable: ^0.5.0
  image_picker: ^1.1.2
  google_mobile_ads: ^5.0.0
#  pdf_maker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
#  file_saver: ^0.3.1
#  document_file_save_plus: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/json/
    - assets/image/
    - assets/fonts/

  fonts:
    - family: gelasio
      fonts:
        - asset: assets/fonts/Gelasio-400.ttf
        - asset: assets/fonts/Gelasio-500.ttf
        - asset: assets/fonts/Gelasio-600.ttf
        - asset: assets/fonts/Gelasio-700.ttf
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans.ttf
        - asset: assets/fonts/NotoColorEmoji.ttf
        - asset: assets/fonts/DejaVuSansMono.ttf
