// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjC-qA6FeTRoIBijmcvyrPByyrTkeMASU',
    appId: '1:570370723208:ios:0e54865ce0a12b3d6ffe3d',
    messagingSenderId: '570370723208',
    projectId: 'my-deficiencies',
    storageBucket: 'my-deficiencies.firebasestorage.app',
    iosBundleId: 'com.ai.my.deficiencies',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBiSMeF0yltpkB3o_jC6jy-P1te2P1X-eQ",
    authDomain: "my-deficiencies.firebaseapp.com",
    projectId: "my-deficiencies",
    storageBucket: "my-deficiencies.firebasestorage.app",
    messagingSenderId: "570370723208",
    appId: "1:570370723208:web:e91fe171d97f79416ffe3d",
    measurementId: "G-CGM33FT1XC"
  );

}